version: '3.9'
services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093, OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093, OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_BROKERCONNECT: "kafka:9093"
    ports:
      - "9000:9000"
  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgres
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./src/main/resources/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
#      - ./dbscripts/postgres:/docker-entrypoint-initdb.d